/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Enquiry {
  'id' : string,
  'customerName' : string,
  'pipeDiameter' : string,
  'orderType' : OrderType,
  'email' : string,
  'requirementsFile' : [] | [ExternalBlob],
  'timestamp' : bigint,
  'quantity' : bigint,
  'phoneNumber' : string,
}
export type ExternalBlob = Uint8Array;
export interface Feedback {
  'id' : string,
  'subject' : string,
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : bigint,
  'phone' : string,
}
export interface Message {
  'id' : string,
  'subject' : string,
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : bigint,
  'phone' : string,
}
export type OrderType = { 'placeOrder' : null } |
  { 'requestQuote' : null };
export interface Product {
  'id' : string,
  'specifications' : string,
  'standards' : string,
  'name' : string,
  'available' : boolean,
  'diameterRange' : string,
  'photo' : [] | [ExternalBlob],
  'price' : [] | [number],
}
export interface SiteSettings {
  'googleMapEmbed' : string,
  'contactLocation' : string,
  'whatsappConfig' : [] | [WhatsAppConfig],
  'contactEmail' : string,
  'companyName' : string,
  'pricingTable' : Array<[string, number]>,
  'certifications' : string,
  'contactPhone' : string,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WhatsAppConfig {
  'prefilledMessage' : [] | [string],
  'phoneNumber' : string,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addProduct' : ActorMethod<[Product], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'authenticateWithAdminPasskey' : ActorMethod<[string], undefined>,
  'getAllEnquiries' : ActorMethod<[], Array<Enquiry>>,
  'getAllFeedback' : ActorMethod<[], Array<Feedback>>,
  'getAllMessages' : ActorMethod<[], Array<Message>>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getPriceForDiameter' : ActorMethod<[string], [] | [number]>,
  'getProduct' : ActorMethod<[string], Product>,
  'getSiteSettings' : ActorMethod<[], SiteSettings>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendMessage' : ActorMethod<[Message], undefined>,
  'submitEnquiry' : ActorMethod<[Enquiry], undefined>,
  'submitFeedback' : ActorMethod<[Feedback], undefined>,
  'updateSiteSettings' : ActorMethod<[SiteSettings], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];